name:                type-checker
version:             0.1.0.0
github:              "mblotiu/type-checker"
license:             BSD-3-Clause
author:              "Mihnea-Andrei Blotiu"
maintainer:          "mblotiu.ss@gmail.com"
copyright:           "2024 Mihnea-Andrei Blotiu"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/type-checker#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- bytestring
- graphviz

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wredundant-constraints
- -Werror

library:
  source-dirs: src

executables:
  type-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-checker

tests:
  type-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-checker
